### PR TITLE
Project: Next web Clone

### PR DESCRIPTION
**Pull request by taiwocoker**
In this Milestone, I added:

-Responsive Navigation Bar
-Different Responsive Sections using Grid
-Footer

### CODE REVIEW

**Comment by Dandush03** [comment]
# :red_circle: Status Require: changes :muscle: 
### Hey :wave: 
## Good attempts on this one :muscle: :+1: 

### This page is a clone page from the [TheNextWeb](https://thenextweb.com/), therefore there are a few changes you have to fix in order to achieve it

## Here are the issues to address to get the project meet the requirement:wink:

### [__NOTICE__]: I would not repeat previews mistake. Make sure you fix them in all views.

---

---

# Phone Resolution (Default Width)
## [__IMPORTANT__] This view had an vertical scrolling bar that can not be there

---

---

## Header
- [ ] Yellow add should be hiding in this view
##### Required:
Screenshot from 2020-04-22 08-34-26
##### Yours: 
Screenshot from 2020-04-22 08-33-56

---

## Latest News
- [ ] Elements need to be aligned
- [ ] Picture should have more height in order to achieve a perfect square 
##### Required:
Screenshot from 2020-04-22 08-34-54
##### Yours: 
Screenshot from 2020-04-22 08-34-44

---

## Latest Funding Round . . .
- [ ] Missing menu
##### Required:
Screenshot from 2020-04-22 08-35-26
##### Yours: 
Screenshot from 2020-04-22 08-35-33


---

## Footer
- [x] Media element should be round not oblique
- [x] Footer elements are not aligned to the center
##### Required:
Screenshot from 2020-04-22 08-36-39
##### Yours: 
Screenshot from 2020-04-22 08-36-47

---

---

# Pad Resolution (min-Width: 768px)

---

---

## [__IMPORTANT__]

### It's behaving the same way as the phone view, please check the original and copy it's behavior

---

---

# Desktop Resolution (min-Width: 1025)

---

---

## First-Section
- [ ] Left Picture TNW logo should be a link
- [ ] This elements are very height, please adjust them as the original page
##### Required:
Screenshot from 2020-04-22 08-29-58
##### Yours: 
Screenshot from 2020-04-22 08-29-43

---

## App, Gear, Tech . . . . Section
- [ ] sub image is not aligned with the title on its left
##### Required:
Screenshot from 2020-04-22 08-30-37
##### Yours: 
Screenshot from 2020-04-22 08-30-24

---

## Kindly address all these changes and submit a new code review

### Happy coding:computer: 

#### Daniel Laloush

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes ♻️ 🚥 

Hi @taiwocoker, congratulations on a great job 👍 we fixed almost all the comments by the previous TSE 🙂 , However, to improve our code and to meet  all the minimum requirements, let us address the comments below: 👍 
- Let us reduce the ```margin-top``` between the nav and the content so it appears like the original. Currently
mg
- The pricing text in the ```latest news``` section is currently out of place, let us address it
mg1
- Kindly center the elements in the footer as in the original
```Currently```
mg2
```Original```
mg3
- Kindly hide the fourth element, in the original there is only 3 elements on a row
mg4
- Kindly reposition the text so it appears on the bottom on ```medium``` screen
mg5
- Let us apply the DRY rule so we do not repeat code. The image below shows an example of code we can apply DRY rule to
mg6


Kindly make these changes and submit another code review 😄 
_Happy coding_ 👨‍💻 
Daniel Larbi Addo on slack

**Comment by sumancrest0001** [comment]
**Great work @taiwocoker  :clap: :clap:** 
You have made most of the changes requested by the previous TSEs. The page looks responsive but we have to fix small issues like alignment, text-size, margin, and padding. Please fix the following issues.
[Required] The TNW logo should be removed from the main article on a small and medium screen. Try to reduce the font-size of the other two articles for medium screen so that it looks similar to the original one.
**Currently :point_down:  :point_down:** 
Screenshot from 2020-04-23 15-29-38
It should be like this :point_down:  :point_down: 
Screenshot from 2020-04-23 15-36-58

**Comment by sumancrest0001** [comment]
[Required] Fix alignment of text with image currently they are not aligned properly.
Screenshot from 2020-04-23 15-26-31

On the original page :point_down: 
Screenshot from 2020-04-23 15-26-18

**Comment by sumancrest0001** [comment]
**ON SMALL SCREEN**
[Required] Let's fix the alignment of images on the subsection of App, Insight sections to make it better visually.
currently :point_down: 
Screenshot from 2020-04-23 15-23-17

On the original one  :point_down: 
Screenshot from 2020-04-23 15-54-30

**Comment by sumancrest0001** [comment]
[Required] On the latest deal section. Currently, the price is overlapping with the image. We have to fix this issue.
On your  project :point_down: 
Screenshot from 2020-04-23 15-24-16

it should be like this :point_down: 
Screenshot from 2020-04-23 15-57-27

**Review by sumancrest0001 — CHANGES_REQUESTED** [review]
**Please fix the above-requested changes and submit the project for another review. 
We are very close to getting approved.**

Have any additional queries? DM me on slack **Suman Shrestha**
Happy coding

**Comment by mikenath223** [comment]
### Pull request currently under review by Michgolden Ukeje (TSE).
Kindly exercise patience 👋

**Review by mikenath223 — CHANGES_REQUESTED** [review]
Hi @taiwocoker  👋

You've done good on this project. Thumbs up working with previous reviews to get your project to this stage. 👍👍

However, there remain a few more changes to be made to get your final thumbs-up, kindly hang in there.

- [ ] - There is an issue with the way the `Latest Funding Round` text flows above the header when the document scrolls to the `Latest Funding Round Section`. Please fix this.
**THIS IS YOURS👇**
ice_screenshot_20200423-133213

- [ ] In addition, kindly notice the difference in both color and height of the footer section. You can use a color picker extension to get the exact color of the original webpage and change yours accordingly. You can consider using [this chrome extension](https://chrome.google.com/webstore/detail/colorzilla/bhlhnicpbhignbdhedgjhgdocnmhomnp) if chrome is your default browser.
**THIS IS YOURS**👇
ice_screenshot_20200423-132643

**THIS IS WHAT IS EXPECTED**👇
ice_screenshot_20200423-132551


***
TABLET AND MOBILE SCREEN SIZE
***
 - [ ] On tablet and mobile screen sizes kindly notice that there are three templates on the `Latest Funding Rounds` section. This is in contrast to yours which appears to be four.
**THIS IS YOURS**👇
ice_screenshot_20200423-132438

**THIS IS WHAT IS EXPECTED**👇
ice_screenshot_20200423-133731

- [ ] Also kindly note that the header logo begins to be visible both on a tablet screen size and a mobile screen size.
**THIS IS WHAT IS EXPECTED ON BOTH TABLET AND MOBILE**👇
ice_screenshot_20200423-132730

***
MOBILE SCREEN-SIZE
***
- [ ] On a mobile screen-size the footer social icons look quite out of place, kindly compare to the original webpage and amend it.
**THIS IS YOURS**👇
ice_screenshot_20200423-135024

**THIS IS YOURS**👇
ice_screenshot_20200423-135041

Kindly fix these issues and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

HAPPY CODING👨‍💻

**Review by mikenath223 — APPROVED** [review]
### CONGRATULATIONS  👏👏👏

This project meets the requirements for approval.

**STATUS: APPROVED ✅**


Don't forget to fill the project completion form👍
Good luck with the next project.

HAPPY CODING👨‍💻

**Pull request merged**
